# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996ad937d78dd05f6ee5b3f091bf48688769b140f6e4e9f69eb8656edc7251cac363ea0f8499f94e08f1822276e63c8dd36e5765146b9572844b5acea02b4ae9

test:
  secret_key_base: 409ac5e44411c8b4dcdc1115011a015f1cd3ef0081a26c3bff14f43d268ddb75896577537c5446bbdde924f447c423959bbc8a673a0b00828ff39dbc0edd4187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
